services:
  app:
    build: .
    container_name: wasap-scheduler
    # ports:
    #   - "3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./schedules.db:/app/schedules.db
      - ./auth:/app/auth
    networks:
      - mynetwork
networks:
  mynetwork:
